language: node_js
node_js:
  - "node"
after_success:
  - "node_modules/.bin/reactor-sandbox build"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
